name: Deploy with Github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel in-progress runs
        if: github.event_name == 'push'
        run: |
          curl -X DELETE \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            https://api.github.com/repos/mtemkit/Python-Discord-AI-Chat-Bot/actions/runs?event_

  deploy:
    runs-on: ubuntu-latest
    concurrency: 1
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies & Run the Bot
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt   
          python main.py