name: Deploy with Github Actions

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: 1
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies & Run the Bot
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt   
          python main.py
    cancel-in-progress: true
