name: Deploy to Firebase

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Run Discord bot
        run: |
          python -m venv venv
          source venv/bin/activate
          echo "Setting environment variables..."
          CHATGPT_API_KEY=${{ secrets.CHATGPT_API_KEY }}
          DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
          pip install -r requirements.txt   
          python chatbot.py
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase use --token $FIREBASE_TOKEN
          firebase deploy --token $FIREBASE_TOKEN
